### ISSUE TITLE
Use npm packages for email validation

### ISSUE THREAD

**Issue by kevinnguyen20** [Kollektives-Plagiieren/innovative-commercial-market#1]
# Description

The current implementation of the email validation is based on a regex which should cover the most common cases. However, it might be benificial to make use of npm packages dealing with email validation.

The respective file is located at `app/controllers/validation.server.controller.js`.

# References

* Example: https://github.com/manishsaraan/email-validator

**Comment by corners2wall** [comment]
For this goal maybe use [yup](https://github.com/jquense/yup). Later you need other schemas by shape. It's not bad tool for validation. I can do it. Would you assign it to me?

**Comment by corners2wall** [comment]
@kevinnguyen20 You can validate your api request schema, query and path parameter. Maybe this validations necessary in future

**Comment by kevinnguyen20** [comment]
@corners2wall, we will certainly take your suggestion into consideration in the near future. However, at the moment, the proposed approach seems to meet our current needs adequately.

**Comment by krutarth4** [comment]
@kevinnguyen20  Email validation package is ready for merge !
