### ISSUE TITLE
Toast error notifications

### ISSUE THREAD

**Issue by kevinnguyen20** [Kollektives-Plagiieren/innovative-commercial-market#5]
# Description

When we log in (or out) successfully, a notification will be displayed on the screen. However, a notification should also appear when the process of authentication fails. It is implemented in the code but, e.g., when we submit an empty form on the `/login` path, the error is only shown in the browser's console.

**Comment by krutarth4** [comment]
@kevinnguyen20 I think normal dialogue box is better than Toast notification for this particular case.

**Comment by kevinnguyen20** [comment]
@krutarth4 I think you are right. Do you want to implement this feature (in a separate issue)?

**Comment by kevinnguyen20** [comment]
React-toastify has been removed completely from our project.
